version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: user-api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

