import { Router } from "express";
import signupRouter from "./signup";
import resetPasswordRouter from "./reset-password";
import signinRouter from "./signin";
import createPasswordRouter from "./create-password";
import generateNewTokenRouter from "./generate-new-token";
import validationTokenRouter from "./validation-token";
const routes = Router();
routes.use('/sign-up', signupRouter);
routes.use('/token-validation', validationTokenRouter);
routes.use('/generate-new-token', generateNewTokenRouter);
routes.use('/sign-in', signinRouter);
routes.use('/reset-password', resetPasswordRouter);
routes.use('/create-password', createPasswordRouter);
export default routes;
