export enum RabbitMqQueues {
    CREATE_TOKEN = 'CREATE_TOKEN',
    VALIDATE_TOKEN = 'VALIDATE_TOKEN',
    USER_RESPONSE_QUEUE = 'USER_RESPONSE_QUEUE',
    CREATE_SESSION = 'CREATE_SESSION',
    UPDATE_USER_WITH_PROFILE_DATA = 'UPDATE_USER_WITH_PROFILE_DATA',
    CHECK_PHONE_NUMBER_DISPONIBILITY = 'CHECK_PHONE_NUMBER_DISPONIBILITY',
};
