export enum RabbitMqQueues {
    CREATE_TOKEN = 'CREATE_TOKEN',
    VALIDATE_TOKEN = 'VALIDATE_TOKEN',
    USER_RESPONSE_QUEUE = 'USER_RESPONSE_QUEUE',
    CREATE_SESSION = 'CREATE_SESSION',
    UPDATE_USER_WITH_SELECTED_PROFILE_ID = 'UPDATE_USER_WITH_SELECTED_PROFILE_ID',
    UPDATE_USER_WITH_PHONE_NUMBER = 'UPDATE_USER_WITH_PHONE_NUMBER',
    CHECK_PHONE_NUMBER_DISPONIBILITY = 'CHECK_PHONE_NUMBER_DISPONIBILITY',
    CHECK_EMAIL_DISPONIBILITY = 'CHECK_EMAIL_DISPONIBILITY',
    CREATE_PROFILE_AFTER_SIGNUP = 'CREATE_PROFILE_AFTER_SIGNUP',
};
